import {
  REDIRECT_URI,
  SCOPE,
  RESPONSE_TYPE,
  CLIENT_ID,
  CDN_IMAGE,
} from "./discordAuth";

import { COLLECTION_USERS, COLLECTION_APPOINTMENTS } from "./database";

export {
  REDIRECT_URI,
  SCOPE,
  RESPONSE_TYPE,
  CLIENT_ID,
  CDN_IMAGE,
  COLLECTION_USERS,
  COLLECTION_APPOINTMENTS,
};
