export { default as Ranked } from "./ranked.svg";
export { default as Player } from "./player.svg";
export { default as Training } from "./training.svg";
export { default as Duel } from "./duel.svg";
export { default as Fun } from "./fun.svg";
export { default as Calendar } from "./calendar.svg";
export { default as LeeSin } from "./illustration.png";
export { default as Discord } from "./discord.png";
export { default as Banner } from "./banner.png";
